version: "3.8"
services:
  spring:
    container_name: backend-spring-app
    build: .
    expose:
      - 8100
    ports:
      - "8100:8100"
    volumes:
      - .:/app
    environment:
      server.ssl.key-password: ${KEY_PW}
      server.ssl.key-store-password: ${KEY_PW}
      spring.datasource.driverClassName: "org.mariadb.jdbc.Driver"
      spring.datasource.url: ${RDS_URL}
      spring.datasource.username: ${RDS_USER}
      spring.datasource.password: ${RDS_PW}
