version: "3.8"
services:
  spring:
    container_name: backend-spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
      - spring.datasource.url=${RDS_URL}
      - spring.datasource.username=${RDS_USER}
      - spring.datasource.password=${RDS_PW}
      - TZ=Asia/Seoul
    volumes:
      - ./src/main/resources:/app/resources
    restart: unless-stopped
