spring:
  profiles:
    active: local
  datasource:
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always

server:
  port: 8100
  error:
    include-exception: true
    include-stacktrace: always

logging:
  level:
    org:
      springframework:
        security: DEBUG
        jdbc:
          datasource:
            init:
              ScriptUtils: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker-compose
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  sql:
    init:
      mode: never

server:
  port: 8100
  error:
    include-exception: false
    include-stacktrace: never
