spring:
  profiles:
    active: localhost

---
spring:
  profiles: local
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
      path: /h2-console
      settings: 
        web-allow-others: true
  sql:
    init:
      mode: always
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
server:
  port: 8100
  error:
    include-exception: true
    include-stacktrace: always

---
spring:
  profiles: docker-compose
  jpa:
    hibernate:
      ddl-auto: update
server:
  ssl:
    enable: true
    key-store: "classpath:keystore.p12"
  #     key-store-password: '${KEY_PW}'
  #     key-password: '${KEY_PW}'
  port: 8100
