spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always

server:
  port: 8100
  error:
    include-exception: true
    include-stacktrace: always

logging:
  level:
    org:
      springframework:
        security: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker-compose
  jpa:
    hibernate:
      ddl-auto: update
server:
  ssl:
    enable: true
    key-store: "classpath:keystore.p12"
  #     key-store-password: '${KEY_PW}'
  #     key-password: '${KEY_PW}'
  port: 8100