spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: spring
    password: 1
    url: jdbc:mariadb://111.111.111.111:3306/spring
  jpa:
    #    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: never

server:
  port: 8100
  error:
    include-exception: true
    include-stacktrace: always

logging:
  level:
    org:
      springframework:
        security: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker-compose
  jpa:
    hibernate:
      ddl-auto: update
server:
  ssl:
    enable: true
    key-store: "classpath:keystore.p12"
  #     key-store-password: '${KEY_PW}'
  #     key-password: '${KEY_PW}'
  port: 8100
